language: node_js
node_js:
    - "8"
cache:
  directories:
    - node_modules
notifications:
  email: false

branches:
  only:
    - master
    - dev

before_install:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      git clone "https://github.com/$TRAVIS_REPO_SLUG.git" "$TRAVIS_REPO_SLUG";
      cd "$TRAVIS_REPO_SLUG";
      git checkout -qf "$TRAVIS_COMMIT";
    fi
  - npm install -g npm
install:
  - npm prune
  - npm install
  - npm update

before_deploy:
  - git config --global user.name "thundernet8"
  - git config --global user.email "wuxueqian2010@hotmail.com"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials
  - git checkout master
  - npm run automatic-release

deploy:
  provider: npm
  email: wuxueqian2010@icloud.com
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    branch: master
    repo: thundernet8/customized-progress-webpack-plugin
after_deploy:
  - npm run list-deployed-files